[platformio]
src_dir = swift_show_tuning

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM16
upload_speed = 921600
board_build.partitions = default.csv
