#!/usr/bin/env python3
"""Draw the dashboard's home-screen icon and write it to swift_show_tuning/web_icon.h.

The firmware serves the PNG at /icon.png: apple-touch-icon (iPhone "Főképernyőhöz adás"),
the web app manifest icon (Android) and the favicon. A dark neon tachometer in the
dashboard's colours, needle in the red zone. Everything stays inside the centre circle of
80 % diameter, so the same image is also a valid "maskable" icon.

Needs Pillow (pip install pillow).

Usage (from anywhere):
    python tools/ui/make_icon.py              write swift_show_tuning/web_icon.h
    python tools/ui/make_icon.py --png FILE   also write the PNG to FILE (to look at it)
"""
import argparse
import io
import math
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parents[2]
HEADER = ROOT / "swift_show_tuning" / "web_icon.h"
SIZE = 192           # one PNG for iOS (180 recommended, scaled) and the manifest (192)
SS = 4               # supersampling for smooth edges
BG_TOP, BG = (0x15, 0x1D, 0x2C), (0x07, 0x09, 0x0E)
CYAN, AMBER, RED = (0x00, 0xF0, 0xFF), (0xFF, 0xAA, 0x00), (0xFF, 0x22, 0x47)
WHITE = (0xF0, 0xF4, 0xFC)


def draw_icon() -> Image.Image:
    n = SIZE * SS
    s = lambda v: round(v * n)  # noqa: E731  (fraction of the icon -> pixels)

    # Background: the page's radial gradient (lighter at the top centre)
    grad = Image.new("RGB", (SIZE, SIZE))
    grad.putdata([tuple(round(t + (b - t) * min(1.0, math.hypot(x / SIZE - 0.5, y / SIZE) / 0.95))
                        for t, b in zip(BG_TOP, BG))
                  for y in range(SIZE) for x in range(SIZE)])
    img = grad.resize((n, n), Image.BILINEAR)

    cx, cy, r, w = 0.5, 0.53, 0.29, 0.085
    box = [s(cx - r), s(cy - r), s(cx + r), s(cy + r)]
    # PIL angles: degrees clockwise from 3 o'clock. 270° sweep, open at the bottom.
    zones = [(135, 318, CYAN), (318, 350, AMBER), (350, 405, RED)]

    # Neon glow: the arc blurred underneath
    glow = Image.new("RGB", (n, n), (0, 0, 0))
    g = ImageDraw.Draw(glow)
    for a0, a1, col in zones:
        g.arc(box, a0, a1, fill=col, width=s(w * 1.6))
    glow = glow.filter(ImageFilter.GaussianBlur(s(0.035)))
    img = ImageChops.add(img, glow.point(lambda v: round(v * 0.55)))

    d = ImageDraw.Draw(img)
    for a0, a1, col in zones:
        d.arc(box, a0, a1, fill=col, width=s(w))

    # Needle into the red zone, with a hub
    ang = math.radians(372)
    tip = (cx + math.cos(ang) * r * 0.86, cy + math.sin(ang) * r * 0.86)
    back = (cx - math.cos(ang) * r * 0.16, cy - math.sin(ang) * r * 0.16)
    nx, ny = -math.sin(ang), math.cos(ang)
    hw = 0.03
    d.polygon([(s(back[0] + nx * hw), s(back[1] + ny * hw)), (s(tip[0]), s(tip[1])),
               (s(back[0] - nx * hw), s(back[1] - ny * hw))], fill=WHITE)
    hub = 0.06
    d.ellipse([s(cx - hub), s(cy - hub), s(cx + hub), s(cy + hub)], fill=RED)
    hub2 = 0.026
    d.ellipse([s(cx - hub2), s(cy - hub2), s(cx + hub2), s(cy + hub2)], fill=BG)

    # Spark bolt in the opening at the bottom (the spark cut)
    bolt = [(0.525, 0.715), (0.450, 0.815), (0.495, 0.815), (0.475, 0.890),
            (0.555, 0.785), (0.508, 0.785)]
    d.polygon([(s(x), s(y)) for x, y in bolt], fill=AMBER)

    return img.resize((SIZE, SIZE), Image.LANCZOS)


def encode_png(img: Image.Image) -> bytes:
    """128-colour palette PNG: ~4 KB of flash, no visible banding on the dark gradient."""
    buf = io.BytesIO()
    img.quantize(colors=128, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE).save(
        buf, format="PNG", optimize=True)
    return buf.getvalue()


def header_text(png: bytes) -> str:
    lines = [", ".join("0x%02x" % b for b in png[i:i + 16]) for i in range(0, len(png), 16)]
    body = ",\n  ".join(lines)
    return (
        "#pragma once\n"
        "// Home-screen icon of the dashboard (%dx%d PNG, %d bytes), served at /icon.png as the\n"
        "// apple-touch-icon, the web app manifest icon and the favicon (swift_show_tuning.ino).\n"
        "// GENERATED by tools/ui/make_icon.py - edit the drawing there, then rerun it.\n"
        "#include <Arduino.h>\n"
        "\n"
        "const uint8_t WEB_ICON_PNG[] PROGMEM = {\n"
        "  %s\n"
        "};\n" % (SIZE, SIZE, len(png), body)
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--png", metavar="FILE", help="also write the PNG to FILE")
    args = ap.parse_args()

    png = encode_png(draw_icon())
    HEADER.write_text(header_text(png), encoding="utf-8", newline="\n")
    print(f"wrote {HEADER.relative_to(ROOT)}: {SIZE}x{SIZE} PNG, {len(png)} bytes")
    if args.png:
        Path(args.png).write_bytes(png)
        print(f"wrote {args.png}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
